# Generated by Django 5.0.1 on 2024-04-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarypatrons', '0003_contactus_alter_bookapplicants_id_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookapplicants',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
